# Generated by Django 3.0.8 on 2021-01-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_mcq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='options',
            new_name='option1',
        ),
        migrations.AddField(
            model_name='mcq',
            name='option2',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='option3',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='option4',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
