# Generated by Django 3.0.8 on 2021-01-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210124_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='multiple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
