# Generated by Django 3.0.8 on 2021-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_mcq_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField()),
                ('answer_text', models.CharField(max_length=2000)),
                ('explanation_text', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=2000)),
            ],
        ),
    ]
