# Generated by Django 3.0.8 on 2021-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='written',
            name='display_answer',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
