# Generated by Django 3.0.8 on 2021-04-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_written_display_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField()),
                ('answer_text', models.CharField(max_length=2000)),
                ('explanation_text', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=2000)),
                ('display_answer', models.CharField(max_length=2000)),
                ('isTimed', models.BooleanField()),
                ('image_1', models.ImageField(upload_to='')),
            ],
        ),
    ]
