# Generated by Django 3.0.8 on 2021-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='image_2',
            field=models.ImageField(default='A', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='image_3',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='image_4',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
