# Generated by Django 3.0.8 on 2021-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210410_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='hint_text',
            field=models.CharField(default='ok', max_length=2000),
            preserve_default=False,
        ),
    ]
