# Generated by Django 3.0.8 on 2021-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_connect_hint_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVisual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField()),
                ('answer_text', models.CharField(max_length=2000)),
                ('explanation_text', models.CharField(max_length=2000)),
                ('hint_text', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=2000)),
                ('display_answer', models.CharField(max_length=2000)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('audio', models.FileField(null=True, upload_to='audios/', verbose_name='')),
            ],
        ),
    ]
