# Generated by Django 3.0.8 on 2021-06-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_audiovisual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovisual',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='audiovisual',
            name='video',
        ),
    ]
