# Generated by Django 3.0.8 on 2021-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210622_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisual',
            name='is_Audio',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiovisual',
            name='is_Video',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
