# Generated by Django 3.0.8 on 2021-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210622_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisual',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='audiovisual',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
