# Generated by Django 3.0.8 on 2021-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210622_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('answer_text', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=2000)),
            ],
        ),
    ]
