# Generated by Django 3.0.8 on 2021-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('event', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=2000)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='')),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('is_Image', models.BooleanField()),
                ('is_Audio', models.BooleanField()),
                ('is_Video', models.BooleanField()),
            ],
        ),
    ]
